### PR TITLE
Restore getCharFromKey that uses toLocale*Case

### PR DESCRIPTION
**Pull request by DLowHP**

### CODE REVIEW

**Comment by qiufeihong2018** [comment]
@DLowHP You must call `isAlphaNumericKey`

**Comment by DLowHP** [comment]
Where?

**Comment by qiufeihong2018** [comment]
In handleKeyDown, it must be judged that the pressed key code is alphanumeric and not when the Shift and Space keys are pressed. The function will return the updated cell object and set enableEditMode to true. Otherwise, if the pressed key code is a mouse pointer key or the Enter key, the function returns the original cell object and sets enableEditMode to true.

**Comment by qiufeihong2018** [comment]
@DLowHP 
```js
    handleKeyDown(cell: Compatible<TextCell>, keyCode: number, ctrl: boolean, shift: boolean, alt: boolean, key: string): { cell: Compatible<TextCell>, enableEditMode: boolean } {
        const char = getCharFromKey(key, shift);

        if (!ctrl && !alt && isAlphaNumericKey(keyCode) && !(shift && keyCode === keyCodes.SPACE))
            return { cell: this.getCompatibleCell({ ...cell, text: char }), enableEditMode: true }
        return { cell, enableEditMode: keyCode === keyCodes.POINTER || keyCode === keyCodes.ENTER }
    }
```

**Comment by DLowHP** [comment]
Well, not really. We don't need `isAlphaNumericKey` because in the place of it there is `isKeyPrintable` function that achieves the same effect.

**Comment by qiufeihong2018** [comment]
@DLowHP If you use `isKeyPrintable`, then when inputting Chinese or other input methods, the first character will always be English.
```
/**
 * Helper function to check that the provided `key` produces printable character
 * @param key field from `KeyboardEvent` interface
 * @returns Returns `true` if `key` is one of printable characters
 */
export const isKeyPrintable = (key: string): boolean => key.length === 1;

```

**Comment by qiufeihong2018** [comment]
image

**Comment by DLowHP** [comment]
I beg to differ, I tested this on my machine and it inputs the proper characters 🤔

https://github.com/silevis/reactgrid/assets/65829376/dbfee8cd-79ae-4c74-af41-5a71b8f31823

**Comment by qiufeihong2018** [comment]
image

**Comment by qiufeihong2018** [comment]
截屏2023-10-25 21 19 44

**Comment by qiufeihong2018** [comment]
chrome-capture-2023-9-25 (2)

**Comment by DLowHP** [comment]
Are you on `develop`? What language settings are you using? What keys did you press so that it somehow returned you a string with letter "f" inside? Also, please show me your getCharFromKey function.

**Comment by qiufeihong2018** [comment]
@DLowHP In fix/first-characters, Chinese input method, press caps lock to switch from English input method to Chinese input method, and then press f

```

export const getCharFromKey = (key: string, isShiftKey = false): string => {
  const language = navigator.language || "en-US";
  return !isShiftKey
    ? key.toLocaleLowerCase(language)
    : key.toLocaleUpperCase(language);
};

```

**Comment by qiufeihong2018** [comment]
@DLowHP I ran your branch `fix/restore-old-get-char-fn`, and there was a problem when testing it locally. The first character was still in English.

image



chrome-capture-2023-9-25 (4)

**Comment by qiufeihong2018** [comment]
chrome-capture-2023-9-25 (4)

**Comment by qiufeihong2018** [comment]
> I beg to differ, I tested this on my machine and it inputs the proper characters 🤔
> 
>  Nagrywanie.2023-10-25.151359.-.Trim.mp4

Strange, I can't solve the problem using this branch. How did you solve it? How did you switch the input method?

**Comment by DLowHP** [comment]
The issue isn't with any of this functions. On your screenshot I can see that your browser returns the wrong key in the keydown event:
image

I'm not sure why, tho...

**Comment by qiufeihong2018** [comment]
@DLowHP This is because under the Chinese input method, when using the keydown event, most keyboard ASCII code values are 229, and the input method automatically adds a value. Therefore, the keyup event should be used regardless of the input method, so that the keyCode of the keyboard can be obtained normally.

**Comment by DLowHP** [comment]
But my problem is with the `key: "f"` value, not the `keyCode: 229`. The 229 value of keyCode means that the input method is still processing, but then the key should return "Process" instead of the keyboard's pressed key as it does in your example

**Comment by qiufeihong2018** [comment]
Why the key return 'Process', I don't see the logic

**Comment by qiufeihong2018** [comment]
If you cannot return to Process, I recommend using https://github.com/silevis/reactgrid/pull/254

**Comment by DLowHP** [comment]
Okay, if you say it works then let's use your solution

**Pull request closed without merging**
