### PR TITLE
Feat/allow extend paste range

### PR DESCRIPTION
**Pull request by qiufeihong2018**
Sorry, there's still a problem with scaling, don't merge, I need to optimize

### CODE REVIEW

**Comment by qiufeihong2018** [comment]
This requirement was fulfilled：Copy a range of cells and paste it into another range, extending the target range if it is too small.
```js
   /** Set `true` to allow pasting cells outside of the grid (by default `false`) */
    readonly allowExtendPasteRange?: boolean;
```

Feat:allow extend paste range

**Comment by qiufeihong2018** [comment]
@DLowHP Please help to review whether these PR can be combined

**Comment by Michota** [comment]
[We already were asked about it not so long ago](https://github.com/silevis/reactgrid/issues/236). We don't plan to add this feature in v4. Though we will think about adding this behavior to v5 of ReactGrid. 
If your data overflows the grid, **you can handle this behavior outside of ReactGrid, in your own function**.
But if you are interested to add feature like this to your project that depends on ReactGrid, I suggest you to create a fork, or implement it by yourself by using something like [PatchPackage](https://www.npmjs.com/package/patch-package).

**Comment by qiufeihong2018** [comment]
> [We already were asked about it not so long ago](https://github.com/silevis/reactgrid/issues/236). We don't plan to add this feature in v4. Though we will think about adding this behavior to v5 of ReactGrid. If your data overflows the grid, **you can handle this behavior outside of ReactGrid, in your own function**. But if you are interested to add feature like this to your project that depends on ReactGrid, I suggest you to create a fork, or implement it by yourself by using something like [PatchPackage](https://www.npmjs.com/package/patch-package).

Can I add this functionality to ReactGrid v5

**Pull request closed without merging**
