### PR TITLE
Create getting-started-in-js

### PR DESCRIPTION
**Pull request by amilamujkic**
A lot of people have confusion with using this component in JS instead of Typescript. Therefore, the code is provided.

### CODE REVIEW

**Review by webloopbox — CHANGES_REQUESTED** [review]
It's better to put this code in the reactgrid documentation

**Comment by qiufeihong2018** [comment]
> It's better to put this code in the reactgrid documentation最好把这段代码放在 reactgrid 文档中

yes!

**Comment by amilamujkic** [comment]
Is there a documentation folder?

**Comment by qiufeihong2018** [comment]
It should be this url： https://github.com/silevis/reactgrid-website

**Comment by MichaelMatejko** [comment]
the code is also using request to localhost:8000, that totally doesn't make any sense. Better to put it in the docs

**Pull request closed without merging**
