### PR TITLE
Fix esc key for number cell

### PR DESCRIPTION
**Pull request by alonshmiel**

### CODE REVIEW

**Comment by alonshmiel** [comment]
Hi, 
I made a PR in the past that handles esc key in number cell (cancel the edit).
I forgot the number cell so I added it to this PR.

This is the old PR that was merge.
https://github.com/silevis/reactgrid/pull/97

**Comment by dayron9408** [comment]
still doesn't work in number cells

**Comment by alon-shmiel-sage** [comment]
Hi @dayron9408 , this PR was not merged yet. This is why it doesn't work.
By the way, you can do what I did: you can use cell template and add the line of the blur event.

**Comment by romanstetsyk** [comment]
Any chance this will be merged soon?

**Comment by alonshmiel** [comment]
Hi @romanstetsyk , I suggest you to create a custom template so you can add it to your template without waiting to this approval. It adds you more control.
https://reactgrid.com/docs/4.0/7-api/0-interfaces/5-cell-template/

**Comment by romanstetsyk** [comment]
@alonshmiel You're probably right. Thanks for the suggestion!

**Comment by alon-shmiel-sage** [comment]
@romanstetsyk , you're welcome :)

**Comment by DLowHP** [comment]
I replaced your solution with a (hopefully) safer key press flag and merged the changes. It should now cancel the changes as  expected.

**Pull request merged**
