### PR TITLE
fix: ContextMenu copy and paste error fails(#250)

### PR DESCRIPTION
**Pull request by qiufeihong2018**

### CODE REVIEW

**Review by DLowHP — APPROVED** [review]
`.filter(Boolean)` looks kind of hacky and I believe the source of the problem is elsewhere but I'm prone to approve this as it achieves the expected result.

**Comment by qiufeihong2018** [comment]
@DLowHP Using the newline character "\n" to split will result in an empty string.

image

image

**Comment by qiufeihong2018** [comment]
Ha ha

> `.filter(Boolean)` looks kind of hacky and I believe the source of the problem is elsewhere but I'm prone to approve this as it achieves the expected result. `.filter(Boolean)` 看起来有点笨拙，我相信问题的根源在其他地方，但我倾向于批准这一点，因为它达到了预期的结果。

**Comment by DLowHP** [comment]
I understand but the question is why does the empty string appear here and how could we improve the code to avoid the empty sting entirely and not have to filter it out afterwards...

**Comment by qiufeihong2018** [comment]
@DLowHP Hello, when will you help me merge and send a new package? I want to solve this problem in my project.

**Comment by DLowHP** [comment]
Hi! I gave you an approve, I thought you can merge it yourself 😉

**Comment by qiufeihong2018** [comment]
Weird, I see you gave an approval, but I don't see a merge button.😄

**Comment by DLowHP** [comment]
No worries, I merged it when I read your previous message ✌🏻

**Pull request merged**
